# Generated by Django 2.0.3 on 2018-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=65535)),
                ('original_lang', models.CharField(max_length=65535)),
                ('translation', models.CharField(max_length=65535)),
            ],
        ),
    ]
